<a href="https://colab.research.google.com/github/harshareddy2608/Pytorch_learning/blob/main/Day_2_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Getting information from tensor
 1. Tensors not right datatype-to get datatype from a tensor,can use tensor.dtype.
 2. Tensors not right shape- to get shape from a tensor,can use tensor.shape
 3. Tensors not on the right device- to get device from a tensor,can use tensor.device

In [ ]:
import torch#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.2577, 0.0236, 0.8941, 0.4965],
        [0.7653, 0.8234, 0.4127, 0.6602],
        [0.3145, 0.0717, 0.0918, 0.4941]])

In [ ]:
#finding out details about some tensors
print(some_tensor)
print(f"datatype pf tensor:{some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"device tensor is on:{some_tensor.device}")

tensor([[0.5391, 0.1398, 0.9149, 0.0443],
        [0.6978, 0.5249, 0.9629, 0.6215],
        [0.1882, 0.1824, 0.7058, 0.2635]])
datatype pf tensor:torch.float32
shape of tensor:torch.Size([3, 4])
device tensor is on:cpu


#performing tensors operations

types of tensor operations are:
1. addition
2.subtraction
3.multiplication
4.division
5.matrix multiplicaation

In [ ]:
#performing addition operation on tensors
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [ ]:
#multiplication of tensor

tensor *10

tensor([10, 20, 30])

In [ ]:
#subtraction of the tensor

tensor - 7

tensor([-6, -5, -4])

In [ ]:
#trying out the pytorch inbuilt functions

torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
#using mulltipilcation fun
torch.add(tensor,15)


tensor([16, 17, 18])

In [ ]:
#using div fun
torch.div(tensor,2)

tensor([0.5000, 1.0000, 1.5000])

#Matrix multiplication in the tensor

there are 2 main ways of performing the matrix multiplicatio int the tensor:-

1. element-wise multiplication
2. matrix multplication

In [ ]:
#element wise multiplication
print(tensor, "*",tensor)
print(f"equals:{tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals:tensor([1, 4, 9])


In [ ]:
#matrix multiplication
torch.matmul(tensor, tensor)


tensor(14)

In [ ]:
1*1 + 2*2 + 3*3

14

In [ ]:
## it gives us the time also of cpu
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 3.3 ms, sys: 18 µs, total: 3.32 ms
Wall time: 3.19 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 501 µs, sys: 0 ns, total: 501 µs
Wall time: 413 µs


tensor(14)

In [ ]:
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,9],
                       [9,10]])

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10,  9, 10]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  26,  29],
        [ 61,  60,  67],
        [ 95,  94, 105]])

In [ ]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

Tensor aggregation operations:-

min,max,mean,sum,etc


In [ ]:
#create a tensor

In [ ]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
#find the min
torch.min(x),x.max()

(tensor(0), tensor(90))

In [ ]:
#finding the mean
torch.mean(x.type(torch.float32)),

(tensor(45.),)

In [ ]:
#finding the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
 #argmin stands for the position of tensor that has a minimum value

 x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
#argmax gives the position of tensor that has max value
x.argmax

<function Tensor.argmax>

In [ ]:
x[9]

tensor(90)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## reshaping,stacking ,squeezing and unsqueezing of the tensors

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z= x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stack tensors on the top of each other
x_stacked= torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#squeezing - removing all single dimensions from a target tensor
print(f"Previous tensor:{x_reshaped}")
print(f"previous shape:{x_reshaped.shape}")

#removing the extra dimension from x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor:{x_squeezed}")
print(f"New shape:{x_squeezed.shape}")

Previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape:torch.Size([1, 9])

New tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape:torch.Size([9])


In [ ]:
#unsqueezing - adding a single dimension to a target tensor at a specific dim
print(f"previous target:{x_squeezed}")
print(f"previous shape:{x_squeezed.shape}")

#adding extra dimension with the sequence
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tesor:{x_unsqueezed}")
print(F"New shape:{x_unsqueezed.shape}")

previous target:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape:torch.Size([9])

New tesor:tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape:torch.Size([9, 1])


In [ ]:
# permute operation - rearranges the dimensions of a target tensor in a specified order
x_orginal= torch.rand(size=(224,224,3))

x_permuted = x_orginal.permute(2,0,1)
print(f"previous shape:{x_orginal.shape}")
print(f"New shape:{x_permuted.shape}")

previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


Selecting data from the tensors

In [ ]:
#creatimg a tensor
import torch
x =torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
# we can aso use ":" to selecr "all" of a target

x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
print(x[0][2][2])



tensor(9)


In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## pytorch tensors with numpy

In [ ]:
# numpy array to tensor
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

Lets learn about tensors with numpy more detailed in the upcoming sessions.