<a href="https://colab.research.google.com/github/harshareddy2608/Pytorch_learning/blob/main/Day_1_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

How to import pytorch

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu121


Introduction to Tensors

Creating tensors

In [3]:
#scalar
scalar = torch.tensor(5)
scalar

tensor(5)

In [4]:
#dimension of scalar
scalar.ndim

0

In [5]:
#getting the tensor back
scalar.item()

5

In [6]:
#vector-which has magnitude and direction
vector = torch.tensor([5,5])
vector

tensor([5, 5])

In [20]:
#dimension of vector
vector.ndim

1

In [19]:
vector.shape

torch.Size([2])

In [9]:
#matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
#dimension of matrix
MATRIX.ndim

2

In [12]:
MATRIX [1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
#TENSOR

TENSOR=torch.tensor([[[1,2,3],[4,5,6],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 5]]])

In [21]:
#dimension of tensor
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR [0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 4, 5]])

## Random tensors

random tensors are important because the way many neural networks learn is that they with the tenors ful of random values

In [25]:
#Creating random tensors of (4,5)
random_tensor = torch.rand(4,5)
random_tensor

tensor([[0.0636, 0.3484, 0.7035, 0.5883, 0.8824],
        [0.6851, 0.6281, 0.7591, 0.6923, 0.3982],
        [0.6938, 0.9676, 0.5455, 0.8373, 0.8681],
        [0.1429, 0.0299, 0.5645, 0.0948, 0.9443]])

In [26]:
#dimension of the random tensor
random_tensor.ndim

2

Zeroes and ones tensors

In [27]:
#creating tensor with all zeros
zeros= torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
#creating tensor with all ones
ones= torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

In [32]:
###Creating a range of tensors

In [33]:
#by using torch.range()
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

Tensor Datatypes

In [40]:
float_32_tensor= torch.tensor([42.0,12.0,55.0])

In [41]:
float_32_tensor.dtype

torch.float32

In [42]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor


tensor([42., 12., 55.], dtype=torch.float16)

lets continue with tensor attributes in next session
